[package]
name = "rs-modbus-stm32-demo"
version = "0.1.0"
edition = "2018"
license = "MIT/Apache-2.0"
repository = "git@github.com:karlp/rs-modbus-stm32-demo.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
